interface shopApi {
  id: number,
  img: string,
  title: string,
  price: number,
  category: string,
  count: number
}

export const shop: shopApi[] = [
  { id: 1, img: '/image/chair.png', category: 'Table', title: 'White Aesthetic Chair', price: 56, count: 0 },
  { id: 2, img: '/image/cupboard.png', category: 'Cupboard', title: 'Wooden Cupboard 3 Row', price: 67, count: 0 },
  { id: 3, img: '/image/chair.png', category: 'Chair', title: 'Minimalist Lounge Chair', price: 24, count: 0 },
  { id: 4, img: '/image/decor1.png', category: 'Decoration', title: 'Working Desk Setup', price: 89, count: 0 },
  { id: 5, img: '/image/decor2.png', category: 'Decoration', title: 'Minimalist White Cuppboard', price: 67, count: 0 },
  { id: 6, img: '/image/decor3.png', category: 'Decoration', title: 'Wooden Dining Table', price: 87, count: 0 },
  { id: 7, img: '/image/decor4.png', category: 'Decoration', title: 'White Minimalist Vase', price: 123, count: 0 },
  { id: 8, img: '/image/decor1.png', category: 'Decoration', title: 'Plant With Clay Stand', price: 76, count: 0 },
  { id: 9, img: '/image/chair.png', category: 'Chair', title: 'White Aesthetic Chair', price: 32, count: 0 },
  { id: 10, img: '/image/cupboard.png', category: 'Cupboard', title: 'Wooden Cupboard 3 Row', price: 45, count: 0 },
  { id: 11, img: '/image/chair.png', category: 'Chair', title: 'Minimalist Lounge Chair', price: 45, count: 0 },
  { id: 12, img: '/image/table.png', category: 'Table', title: 'Working Desk Setup', price: 45, count: 0 },
  { id: 13, img: '/image/cupboard.png', category: 'Cupboard', title: 'Minimalist White Cuppboard', price: 56, count: 0 },
  { id: 14, img: '/image/table.png', category: 'Table', title: 'Wooden Dining Table', price: 56, count: 0 },
  { id: 15, img: '/image/decor2.png', category: 'Decoration', title: 'White Minimalist Vase', price: 34, count: 0 },
  { id: 16, img: '/image/chair.png', category: 'Chair', title: 'Plant With Clay Stand', price: 67, count: 0 },
  { id: 17, img: '/image/chair.png', category: 'Chair', title: 'White Aesthetic Chair', price: 23, count: 0 },
  { id: 18, img: '/image/table.png', category: 'Table', title: 'Wooden Cupboard 3 Row', price: 78, count: 0 },
  { id: 19, img: '/image/chair.png', category: 'Chair', title: 'Minimalist Lounge Chair', price: 12, count: 0 },
  { id: 20, img: '/image/table.png', category: 'Table', title: 'Minimalist White Cuppboard', price: 78, count: 0 },
  { id: 21, img: '/image/table2.png', category: 'Table', title: 'Wooden Dining Table', price: 45, count: 0 },
  { id: 22, img: '/image/decor3.png', category: 'Decoration', title: 'White Minimalist Vase', price: 89, count: 0 },
  { id: 23, img: '/image/decor4.png', category: 'Decoration', title: 'Plant With Clay Stand', price: 99, count: 0 },
  { id: 24, img: '/image/chair.png', category: 'Chair', title: 'White Aesthetic Chair', price: 34, count: 0 },
  { id: 25, img: '/image/cupboard.png', category: 'Cupboard', title: 'Wooden Cupboard 3 Row', price: 67, count: 0 },
  { id: 26, img: '/image/chair.png', category: 'Chair', title: 'Minimalist Lounge Chair', price: 87, count: 0 },
  { id: 27, img: '/image/table.png', category: 'Table', title: 'Working Desk Setup', price: 12, count: 0 },
  { id: 28, img: '/image/cupboard.png', category: 'Cupboard', title: 'Minimalist White Cuppboard', price: 45, count: 0 },
  { id: 29, img: '/image/table2.png', category: 'Table', title: 'Wooden Dining Table', price: 99, count: 0 },
  { id: 30, img: '/image/decor1.png', category: 'Decoration', title: 'White Minimalist Vase', price: 90, count: 0 },
  { id: 31, img: '/image/decor2.png', category: 'Decoration', title: 'Plant With Clay Stand', price: 56, count: 0 },
  { id: 32, img: '/image/chair.png', category: 'Chair', title: 'White Aesthetic Chair', price: 78, count: 0},
  { id: 33, img: '/image/decor3.png', category: 'Decoration', title: 'Wooden Cupboard 3 Row', price: 89, count: 0 },
  { id: 34, img: '/image/chair.png', category: 'Chair', title: 'Minimalist Lounge Chair', price: 45, count: 0 },
  { id: 35, img: '/image/decor4.png', category: 'Decoration', title: 'Plant With Clay Stand', price: 91, count: 0 },
  { id: 36, img: '/image/chair.png', category: 'Chair', title: 'White Aesthetic Chair', price: 55, count: 0 },
  { id: 37, img: '/image/table.png', category: 'Table', title: 'Wooden Dining Table', price: 33, count: 0 },
  { id: 38, img: '/image/table2.png', category: 'Table', title: 'Working Desk Setup', price: 77, count: 0 },
  { id: 39, img: '/image/decor1.png', category: 'Decoration', title: 'White Minimalist Vase', price: 88, count: 0 },
  { id: 40, img: '/image/chair.png', category: 'Chair', title: 'Minimalist Lounge Chair', price: 77, count: 0 },
]